[versions]
# SDK Versions
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
versionCode = "1"
versionName = "1.0.0"

# Plugin versions
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.0"

# Compose
composeBom = "2026.01.01"

# AndroidX Core
coreKtx = "1.17.0"
activityCompose = "1.12.3"

# Lifecycle
lifecycle = "2.10.0"
lifecycleRuntimeKtx = "2.8.7"

# Navigation
navigation3 = "1.1.0-alpha03"
kotlinxSerialization = "1.10.0"

# Koin
koin = "4.1.1"

# Testing
junit = "4.13.2"
junitVersion = "1.3.0"
junit5 = "6.0.2"
espressoCore = "3.7.0"
mockk = "1.14.9"
kluent = "1.73"
turbine = "1.2.1"

# Coroutines
coroutines = "1.10.2"

# Snapshot Testing
roborazzi = "1.57.0"
robolectric = "4.16.1"

# Other
timber = "5.0.1"

# Firebase
firebaseBom = "34.8.0"
googleServices = "4.4.4"
firebaseCrashlyticsPlugin = "3.0.6"

# Detekt
detekt = "1.23.8"
detektComposeRules = "0.5.6"

# Ktlint
ktlint = "1.5.0"
ktlintGradle = "14.0.1"

[libraries]
# Android Gradle Plugin
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Lifecycle
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

# Navigation
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }

# Kotlin Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit5 = { group = "io.insert-koin", name = "koin-test-junit5", version.ref = "koin" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junit5-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
junit5-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit5-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit5-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit5-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kluent = { group = "org.amshove.kluent", name = "kluent", version.ref = "kluent" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# Snapshot Testing
roborazzi-gradlePlugin = { group = "io.github.takahirom.roborazzi", name = "roborazzi-gradle-plugin", version.ref = "roborazzi" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-rule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# Other
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics" }

# Detekt
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-compose-rules = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detektComposeRules" }

# Ktlint
ktlint-gradlePlugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlintGradle" }

[plugins]
# Standard plugins
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }

# Convention plugins
pomodoro-android-application = { id = "pomodoro.android.application", version = "unspecified" }
pomodoro-android-library = { id = "pomodoro.android.library", version = "unspecified" }
pomodoro-android-compose = { id = "pomodoro.android.compose", version = "unspecified" }
pomodoro-android-feature = { id = "pomodoro.android.feature", version = "unspecified" }
pomodoro-android-feature-api = { id = "pomodoro.android.feature.api", version = "unspecified" }
pomodoro-kotlin-library = { id = "pomodoro.kotlin.library", version = "unspecified" }
pomodoro-koin = { id = "pomodoro.koin", version = "unspecified" }
pomodoro-testing = { id = "pomodoro.testing", version = "unspecified" }
pomodoro-android-testing = { id = "pomodoro.android.testing", version = "unspecified" }
pomodoro-roborazzi = { id = "pomodoro.roborazzi", version = "unspecified" }
pomodoro-detekt = { id = "pomodoro.detekt", version = "unspecified" }
pomodoro-ktlint = { id = "pomodoro.ktlint", version = "unspecified" }

